package api.entity;

public class OrderProductKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.product_id
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.order_id
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.product_id
     *
     * @return the value of order_product.product_id
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.product_id
     *
     * @param productId the value for order_product.product_id
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.order_id
     *
     * @return the value of order_product.order_id
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.order_id
     *
     * @param orderId the value for order_product.order_id
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}