package api.entity;

import java.util.Date;

public class OrderProduct extends OrderProductKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.count
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.delete_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.update_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product.create_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.count
     *
     * @return the value of order_product.count
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.count
     *
     * @param count the value for order_product.count
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.delete_time
     *
     * @return the value of order_product.delete_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.delete_time
     *
     * @param deleteTime the value for order_product.delete_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.update_time
     *
     * @return the value of order_product.update_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.update_time
     *
     * @param updateTime the value for order_product.update_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product.create_time
     *
     * @return the value of order_product.create_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product.create_time
     *
     * @param createTime the value for order_product.create_time
     *
     * @mbg.generated Fri Jun 08 17:30:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}